(* DO NOT EDIT THIS FILE: automatically generated by ../configure *)
(* Exact command that generated this file: *)
(* ./configure.ml *)

let local = false
let vmbyteflags = ["-custom";]
let coqlib = "/usr/local/lib/coq"
let configdir = "/etc/xdg/coq"
let datadir = "/usr/local/share/coq"
let docdir = "/usr/local/share/doc/coq"
let coqlibsuffix = "lib/coq"
let configdirsuffix = "/etc/xdg/coq"
let datadirsuffix = "share/coq"
let docdirsuffix = "share/doc/coq"
let ocaml = "/Users/zhangliao/.opam/from_source/bin//ocaml"
let ocamlfind = "/Users/zhangliao/.opam/from_source/bin/ocamlfind"
let ocamllex = "/Users/zhangliao/.opam/from_source/bin//ocamllex"
let camlbin = "/Users/zhangliao/.opam/from_source/bin/"
let camllib = "/Users/zhangliao/.opam/from_source/lib/ocaml"
let camlp5o = "/Users/zhangliao/.opam/from_source/bin/camlp5o"
let camlp5bin = "/Users/zhangliao/.opam/from_source/bin"
let camlp5lib = "/Users/zhangliao/.opam/from_source/lib/camlp5"
let camlp5compat = "-loc loc"
let cflags = "-Wall -Wno-unused -g -O2"
let caml_flags = "-thread -rectypes -w +a-4-9-27-41-42-44-45-48-50-58-59   -safe-string -strict-sequence"
let best = "opt"
let version = "8.9.1"
let caml_version = "4.07.1"
let caml_version_nums = [4;7;1]
let date = "December 2019"
let compile_date = "Dec 3 2019 16:59:28"
let arch = "Darwin"
let arch_is_win32 = false
let exec_extension = ""
let coqideincl = "-I \"/Users/zhangliao/.opam/from_source/lib/lablgtk2\""
let has_coqide = "opt"
let gtk_platform = `X11
let has_natdynlink = true
let natdynlinkflag = "true"
let flambda_flags = []
let vo_magic_number = 8900
let state_magic_number = 58900
let browser = "open %s"
let wwwcoq = "http://coq.inria.fr/"
let wwwbugtracker = "http://coq.inria.fr/bugs/"
let wwwrefman = "http://coq.inria.fr/distrib/V8.9.1/refman/"
let wwwstdlib = "http://coq.inria.fr/distrib/V8.9.1/stdlib/"
let localwwwrefman = "file://usr/local/share/doc/coq/html/refman"
let bytecode_compiler = true
let native_compiler = true

let core_src_dirs = [
  "config";
  "dev";
  "lib";
  "clib";
  "kernel";
  "library";
  "engine";
  "pretyping";
  "interp";
  "parsing";
  "proofs";
  "tactics";
  "toplevel";
  "printing";
  "grammar";
  "ide";
  "stm";
  "vernac";
]

let plugins_dirs = [
  "plugins/btauto";
  "plugins/cc";
  "plugins/derive";
  "plugins/extraction";
  "plugins/firstorder";
  "plugins/funind";
  "plugins/ltac";
  "plugins/micromega";
  "plugins/nsatz";
  "plugins/omega";
  "plugins/quote";
  "plugins/romega";
  "plugins/rtauto";
  "plugins/setoid_ring";
  "plugins/ssr";
  "plugins/ssrmatching";
  "plugins/syntax";
  "plugins/xml";
]

let all_src_dirs = core_src_dirs @ plugins_dirs
